- hosts: all
  become: "{{ sudo | default('yes') }}"
  roles:
    - common
    - streama
  vars:
    # common
    common_ipv4_forward: 1
    common_ssh_port: 2400
    # variabili per ruolo common
    users:
      - name: michele
        authorized:
          - ./keys/michele.pub

